[Service]
ExecStart=
ExecStart=/usr/local/bin/prometheus --config.file=/etc/prometheus/prometheus.yml --storage.tsdb.path=/var/lib/prometheus --web.listen-address=:9091
EOF   
sudo cat /etc/systemd/system/prometheus.service.d/override.conf   
