---
# playbook_pull.yml
- name: Configuration initiale d'une nouvelle machine
  hosts: localhost
  become: yes
  vars:
    repo_url: "https://github.com/dahousse/ansible-lab.git"
    repo_dest: "/opt/ansible-lab"
    playbook_to_run: "site.yml"

  tasks:
    - name: Détecter le gestionnaire de paquets
      set_fact:
        pkg_manager: "{{ 'dnf' if ansible_os_family == 'RedHat' else 'apt' }}"

    - name: Mise à jour du cache des paquets (Debian/Ubuntu)
      apt:
        update_cache: yes
      changed_when: false
      when: pkg_manager == 'apt'

    - name: Mise à jour du cache des paquets (Fedora/RHEL)
      dnf:
        update_cache: yes
      changed_when: false
      when: pkg_manager == 'dnf'

    - name: Installation des dépendances (git, ansible)
      package:
        name:
          - git
          - ansible
        state: present

    - name: Cloner le dépôt de configuration
      git:
        repo: "{{ repo_url }}"
        dest: "{{ repo_dest }}"
        version: main

    - name: Exécuter le playbook principal
      command: "ansible-playbook -i {{ repo_dest }}/hosts {{ repo_dest }}/{{ playbook_to_run }}"
      args:
        chdir: "{{ repo_dest }}"
