---
# site.yml
# Playbook principal d'orchestration de la forteresse.
# Pour lancer la configuration complète : ansible-playbook -i hosts site.yml

- name: Déploiement de la configuration de base
  import_playbook: playbook_base.yml

- name: Déploiement des agents de supervision
  import_playbook: playbook_node_exporter.yml

- name: Déploiement du serveur de métriques
  import_playbook: playbook_prometheus.yml

- name: Déploiement du serveur de visualisation
  import_playbook: playbook_grafana.yml

- name:First Install
  import_playbook: playbook_first_install.yml
