http:
  routers:
    homeassistant:
      rule: "Host(`homeassistant.mysmihome.duckdns.org`)"
      entryPoints:
        - websecure
      service: homeassistant
      tls:
        certResolver: letsencrypt

  services:
    homeassistant:
      loadBalancer:
        servers:
          - url: "http://192.168.1.2:8123"
